// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB52qEIvzumFGx0kNRvnrblp2SXxFpNSo',
    appId: '1:730799011320:web:444d7ad01aacdd75a3120d',
    messagingSenderId: '730799011320',
    projectId: 'ecom-d1f7b',
    authDomain: 'ecom-d1f7b.firebaseapp.com',
    storageBucket: 'ecom-d1f7b.appspot.com',
    measurementId: 'G-C0W7GZ7J3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoO6FONzVC4tCDe_b7Zy8zgRy9n__nUnY',
    appId: '1:730799011320:android:72ffaf68d2217cdda3120d',
    messagingSenderId: '730799011320',
    projectId: 'ecom-d1f7b',
    storageBucket: 'ecom-d1f7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6TVJ7Lu8XjzZUbEDxfBf2MZBluJpehqY',
    appId: '1:730799011320:ios:575e00bb097dd442a3120d',
    messagingSenderId: '730799011320',
    projectId: 'ecom-d1f7b',
    storageBucket: 'ecom-d1f7b.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6TVJ7Lu8XjzZUbEDxfBf2MZBluJpehqY',
    appId: '1:730799011320:ios:575e00bb097dd442a3120d',
    messagingSenderId: '730799011320',
    projectId: 'ecom-d1f7b',
    storageBucket: 'ecom-d1f7b.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB52qEIvzumFGx0kNRvnrblp2SXxFpNSo',
    appId: '1:730799011320:web:0c5fc9e1dd73383ea3120d',
    messagingSenderId: '730799011320',
    projectId: 'ecom-d1f7b',
    authDomain: 'ecom-d1f7b.firebaseapp.com',
    storageBucket: 'ecom-d1f7b.appspot.com',
    measurementId: 'G-R500156K4Y',
  );
}
